imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig', 'php']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum: string
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

ims_common:
    mapping:
        - AppBundle
    translation_fallback: true

fos_rest:
    param_fetcher_listener: true
    body_listener:
        array_normalizer: fos_rest.normalizer.camel_keys
    service:
        exception_handler: api.exception_wrapper_handler
    view:
        view_response_listener: force
        formats:
            json: true
            xml: true
            rss: false
            jsonp: false
    format_listener:
        rules:
            - { path: ^/, fallback_format: json, prefer_extension: false }
    exception:
        enabled: true
        codes:
            'Doctrine\ORM\Query\QueryException':    HTTP_BAD_REQUEST
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT

nelmio_api_doc:
    name: IMS API
    cache:
        enabled: true
    swagger:
        api_base_path:        /v1
        swagger_version:      1.2
        model_naming_strategy: last_segment_only
        api_version:          0.1
        info:
            title:                IMS API
            description:          API for Motortrack Inventory Management System
            TermsOfServiceUrl:    ~
            license:              proprietary
            licenseUrl:           ~

jms_serializer:
    metadata:
        directories:
            IMSCommon:
                namespace_prefix: "IMS\\CommonBundle\Entity"
                path: "@AppBundle/Resources/config/serializer"

knp_paginator:
    page_range: 10
    default_options:
        page_name: _page
        sort_field_name: f23frq2c23f3gfs0d8asfawdf   #random string to disable this parameter, sort handled manually