<?php
// Auto-generated by the console command generate:doctrine:fixtures
// WARNING: Manual editing will be lost when command is run again

namespace AppBundle\DataFixtures\ORM;

use IMS\CommonBundle\Entity\Currency;
use AppBundle\DataFixtures\BaseFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;

class LoadCurrencyData extends BaseFixture implements OrderedFixtureInterface
{
    /**
     * Load data fixtures with the passed EntityManager
     *
     * @param ObjectManager $manager
     */
    public function load(ObjectManager $manager)
    {
        $data = [
            ['name' => 'British Pound','isoCode' => 'GBP'],
        ];
        
        for ($i = 0; $i < 30; $i++) {
            $entity = new Currency();

            $entity->setName(isset($data[$i]['name']) ? $data[$i]['name'] : $this->randomPronounceableWord(1, 5));
            $entity->setIsoCode(isset($data[$i]['isoCode']) ? $data[$i]['isoCode'] : $this->uniqueRandomWord('isoCode', 3, 3));
            $entity->setSymbol($this->randomPronounceableWord(1, 8));
            $entity->setDateAdded(new \DateTime());
            $entity->setDateUpdated(new \DateTime());
            $entity->setStatus(1);
            
            $manager->persist($entity);
            $this->addReference('IMS_CommonBundle_Entity_Currency'.$i, $entity);
        }

        $manager->flush();
    }

    /**
     * Get the order of this fixture
     *
     * @return integer
     */
    public function getOrder()
    {
        return 10;
    }

}