<?php
// Auto-generated by the console command generate:doctrine:fixtures
// WARNING: Manual editing will be lost when command is run again

namespace AppBundle\DataFixtures\ORM;

use IMS\CommonBundle\Entity\TechnicalSpecificationData;
use AppBundle\DataFixtures\BaseFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;

class LoadTechnicalSpecificationDataData extends BaseFixture implements OrderedFixtureInterface
{
    /**
     * Load data fixtures with the passed EntityManager
     *
     * @param ObjectManager $manager
     */
    public function load(ObjectManager $manager)
    {
        
        for ($i = 0; $i < 30; $i++) {
            $entity = new TechnicalSpecificationData();

            $entity->setEngineCylinder($this->randomPronounceableWord(3, 25));
            $entity->setMaxPower($this->randomPronounceableWord(3, 25));
            $entity->setMaxTorque($this->randomPronounceableWord(3, 25));
            $entity->setAcceleration($this->randomPronounceableWord(3, 25));
            $entity->setMaxSpeed($this->randomPronounceableWord(3, 25));
            $entity->setFuelEconomyOne($this->randomPronounceableWord(3, 25));
            $entity->setFuelEconomyTwo($this->randomPronounceableWord(3, 25));
            $entity->setFuelEconomyThree($this->randomPronounceableWord(3, 25));
            $entity->setFuelTankCapacity($this->randomPronounceableWord(3, 25));
            $entity->setCo2Emissions($this->randomPronounceableWord(3, 25));
            $entity->setVehicleTaxBand($this->randomPronounceableWord(3, 25));
            $entity->setVehicleTaxPrice($this->randomPronounceableWord(3, 25));
            $entity->setLength($this->randomPronounceableWord(3, 25));
            $entity->setWidth($this->randomPronounceableWord(3, 25));
            $entity->setHeight($this->randomPronounceableWord(3, 25));
            $entity->setWheelBase($this->randomPronounceableWord(3, 25));
            $entity->setLoadspaceWidth($this->randomPronounceableWord(3, 25));
            $entity->setLoadspaceVolume($this->randomPronounceableWord(3, 25));
            $entity->setVehicleWeight($this->randomPronounceableWord(3, 25));
            $entity->setTowingBrakedTrailer($this->randomPronounceableWord(3, 25));
            $entity->setTowingUnbrakedTrailer($this->randomPronounceableWord(3, 25));
            $entity->setTurningCircle($this->randomPronounceableWord(3, 25));
            $entity->setGroundClearance($this->randomPronounceableWord(3, 25));
            $entity->setApproachAngle($this->randomPronounceableWord(3, 25));
            $entity->setRampBreakoverAngle($this->randomPronounceableWord(3, 25));
            $entity->setDepartureAngle($this->randomPronounceableWord(3, 25));
            $entity->setWadingDepth($this->randomPronounceableWord(3, 25));
            $entity->setDateAdded(new \DateTime());
            $entity->setDateUpdated(new \DateTime());
            $entity->setStatus(1);
            
            $manager->persist($entity);
            $this->addReference('IMS_CommonBundle_Entity_TechnicalSpecificationData'.$i, $entity);
        }

        $manager->flush();
    }

    /**
     * Get the order of this fixture
     *
     * @return integer
     */
    public function getOrder()
    {
        return 30;
    }

}