<?php
// Auto-generated by the console command generate:doctrine:fixtures
// WARNING: Manual editing will be lost when command is run again

namespace AppBundle\DataFixtures\ORM;

use IMS\CommonBundle\Entity\Engine;
use AppBundle\DataFixtures\BaseFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;

class LoadEngineData extends BaseFixture implements OrderedFixtureInterface
{
    /**
     * Load data fixtures with the passed EntityManager
     *
     * @param ObjectManager $manager
     */
    public function load(ObjectManager $manager)
    {
        
        for ($i = 0; $i < 30; $i++) {
            $entity = new Engine();

            $entity->setName($this->randomPronounceableWord(1, 10));
            $entity->setCylinders(mt_rand(1,100));
            $entity->setValves(mt_rand(1,100));
            $entity->setBhp(mt_rand(1,100));
            $entity->setTurbo(mt_rand(1,100));
            $entity->setSupercharger(mt_rand(1,100));
            $entity->setDateAdded(new \DateTime());
            $entity->setDateUpdated(new \DateTime());
            $entity->setIsVerified(rand(0, 1) ? false : true);
            $entity->setStatus(1);
            $entity->setFuel($this->getReference('IMS_CommonBundle_Entity_Fuel'.$i));
            
            $manager->persist($entity);
            $this->addReference('IMS_CommonBundle_Entity_Engine'.$i, $entity);
        }

        $manager->flush();
    }

    /**
     * Get the order of this fixture
     *
     * @return integer
     */
    public function getOrder()
    {
        return 6;
    }

}