<?php
// Auto-generated by the console command generate:doctrine:fixtures
// WARNING: Manual editing will be lost when command is run again

namespace AppBundle\DataFixtures\ORM;

use IMS\CommonBundle\Entity\VehiclePrice;
use AppBundle\DataFixtures\BaseFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;

class LoadVehiclePriceData extends BaseFixture implements OrderedFixtureInterface
{
    /**
     * Load data fixtures with the passed EntityManager
     *
     * @param ObjectManager $manager
     */
    public function load(ObjectManager $manager)
    {
        
        for ($i = 0; $i < 30; $i++) {
            $entity = new VehiclePrice();

            $entity->setPrice(mt_rand(1,100));
            $entity->setPriceType(mt_rand(1,100));
            $entity->setDateAdded(new \DateTime());
            $entity->setDateUpdated(new \DateTime());
            $entity->setCurrency($this->getReference('IMS_CommonBundle_Entity_Currency'.$i));
            $entity->setVehicle($this->getReference('IMS_CommonBundle_Entity_Vehicle'.$i));
            
            $manager->persist($entity);
            $this->addReference('IMS_CommonBundle_Entity_VehiclePrice'.$i, $entity);
        }

        $manager->flush();
    }

    /**
     * Get the order of this fixture
     *
     * @return integer
     */
    public function getOrder()
    {
        return 35;
    }

}