<?php
// Auto-generated by the console command generate:doctrine:fixtures
// WARNING: Manual editing will be lost when command is run again

namespace AppBundle\DataFixtures\ORM;

use IMS\CommonBundle\Entity\Model;
use AppBundle\DataFixtures\BaseFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;

class LoadModelData extends BaseFixture implements OrderedFixtureInterface
{
    /**
     * Load data fixtures with the passed EntityManager
     *
     * @param ObjectManager $manager
     */
    public function load(ObjectManager $manager)
    {
        $data = [
            ['name' => 'thefirstevermodel'],
        ];
        
        for ($i = 0; $i < 30; $i++) {
            $entity = new Model();

            $entity->setName(isset($data[$i]['name']) ? $data[$i]['name'] : $this->randomPronounceableWord(1, 10));
            $entity->setDateAdded(new \DateTime());
            $entity->setDateUpdated(new \DateTime());
            $entity->setIsVerified(rand(0, 1) ? false : true);
            $entity->setStatus(1);
            $entity->setModelGroup($this->getReference('IMS_CommonBundle_Entity_ModelGroup'.$i));
            $entity->setManufacturer($this->getReference('IMS_CommonBundle_Entity_Manufacturer'.($i % 4)));
            if ($this->hasReference('IMS_CommonBundle_Entity_Engine'.$i, $entity)) {
                $entity->addEngine($this->getReference('IMS_CommonBundle_Entity_Engine'.$i));
            }
            if ($this->hasReference('IMS_CommonBundle_Entity_Equipment'.$i, $entity)) {
                $entity->addEquipment($this->getReference('IMS_CommonBundle_Entity_Equipment'.$i));
            }
            if ($this->hasReference('IMS_CommonBundle_Entity_Variant'.$i, $entity)) {
                $entity->addVariant($this->getReference('IMS_CommonBundle_Entity_Variant'.$i));
            }
            
            $manager->persist($entity);
            $this->addReference('IMS_CommonBundle_Entity_Model'.$i, $entity);
        }

        $manager->flush();
    }

    /**
     * Get the order of this fixture
     *
     * @return integer
     */
    public function getOrder()
    {
        return 20;
    }

}