<?php
// Auto-generated by the console command generate:doctrine:fixtures
// WARNING: Manual editing will be lost when command is run again

namespace AppBundle\DataFixtures\ORM;

use IMS\CommonBundle\Entity\TechnicalSpecification;
use AppBundle\DataFixtures\BaseFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;

class LoadTechnicalSpecificationData extends BaseFixture implements OrderedFixtureInterface
{
    /**
     * Load data fixtures with the passed EntityManager
     *
     * @param ObjectManager $manager
     */
    public function load(ObjectManager $manager)
    {
        
        for ($i = 0; $i < 30; $i++) {
            $entity = new TechnicalSpecification();

            $entity->setModelYear(mt_rand(1,100));
            $entity->setDateAdded(new \DateTime());
            $entity->setDateUpdated(new \DateTime());
            $entity->setStatus(1);
            $entity->setTechnicalSpecificationData($this->getReference('IMS_CommonBundle_Entity_TechnicalSpecificationData'.$i));
            $entity->setManufacturer($this->getReference('IMS_CommonBundle_Entity_Manufacturer'.($i % 4)));
            $entity->setModel($this->getReference('IMS_CommonBundle_Entity_Manufacturer'.($i % 4)));
            $entity->setEngine($this->getReference('IMS_CommonBundle_Entity_Manufacturer'.($i % 4)));
            $entity->setVariant($this->getReference('IMS_CommonBundle_Entity_Manufacturer'.($i % 4)));
            $entity->setWheelbase($this->getReference('IMS_CommonBundle_Entity_Manufacturer'.($i % 4)));
            $entity->setBodystyle($this->getReference('IMS_CommonBundle_Entity_Bodystyle'.$i));
            $entity->setTransmission($this->getReference('IMS_CommonBundle_Entity_Transmission'.$i));
            
            $manager->persist($entity);
            $this->addReference('IMS_CommonBundle_Entity_TechnicalSpecification'.$i, $entity);
        }

        $manager->flush();
    }

    /**
     * Get the order of this fixture
     *
     * @return integer
     */
    public function getOrder()
    {
        return 31;
    }

}