IMS\CommonBundle\Entity\Translation\ManufacturerTranslation:
  type: entity
  table: manufacturer_translation
  repositoryClass: Gedmo\Translatable\Entity\Repository\TranslationRepository
  extends: IMS\CommonBundle\Entity\Translation\AbstractTranslation
  indexes:
    idx_manufacturer_translation:
      columns:
        - locale
        - object_class
        - field
        - foreign_key