IMS\CommonBundle\Entity\Translation\WheelbaseTranslation:
  type: entity
  table: wheelbase_translation
  repositoryClass: Gedmo\Translatable\Entity\Repository\TranslationRepository
  extends: IMS\CommonBundle\Entity\Translation\AbstractTranslation
  indexes:
    idx_wheelbase_translation:
      columns:
        - locale
        - object_class
        - field
        - foreign_key