IMS\CommonBundle\Entity\Translation\TrimShadeTranslation:
  type: entity
  table: trim_shade_translation
  repositoryClass: Gedmo\Translatable\Entity\Repository\TranslationRepository
  extends: IMS\CommonBundle\Entity\Translation\AbstractTranslation
  indexes:
    idx_trim_shade_translation:
      columns:
        - locale
        - object_class
        - field
        - foreign_key