IMS\CommonBundle\Entity\Translation\VariantTranslation:
  type: entity
  table: variant_translation
  repositoryClass: Gedmo\Translatable\Entity\Repository\TranslationRepository
  extends: IMS\CommonBundle\Entity\Translation\AbstractTranslation
  indexes:
    idx_variant_translation:
      columns:
        - locale
        - object_class
        - field
        - foreign_key