IMS\CommonBundle\Entity\Translation\EquipmentTypeTranslation:
  type: entity
  table: equipment_type_translation
  repositoryClass: Gedmo\Translatable\Entity\Repository\TranslationRepository
  extends: IMS\CommonBundle\Entity\Translation\AbstractTranslation
  indexes:
    idx_equipment_type_translation:
      columns:
        - locale
        - object_class
        - field
        - foreign_key