IMS\CommonBundle\Entity\Translation\ModelGroupTranslation:
  type: entity
  table: model_group_translation
  repositoryClass: Gedmo\Translatable\Entity\Repository\TranslationRepository
  extends: IMS\CommonBundle\Entity\Translation\AbstractTranslation
  indexes:
    idx_model_group_translation:
      columns:
        - locale
        - object_class
        - field
        - foreign_key