IMS\CommonBundle\Entity\Translation\TransmissionTranslation:
  type: entity
  table: transmission_translation
  repositoryClass: Gedmo\Translatable\Entity\Repository\TranslationRepository
  extends: IMS\CommonBundle\Entity\Translation\AbstractTranslation
  indexes:
    idx_account_translation:
      columns:
        - locale
        - object_class
        - field
        - foreign_key