IMS\CommonBundle\Entity\Variant:
    properties:
        name:
            - NotBlank: ~
            - Length:
                max: 100
        dateAdded:
            - DateTime: ~
        dateUpdated:
            - DateTime: ~
        isVerified:
            - Type:
                type: boolean
        status:
            - Type:
                type: integer